sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
install:
  - bundle install --without development
before_script:
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rake
  - 'cd $TRAVIS_BUILD_DIR/publify_core && bundle exec rake'
  - 'cd $TRAVIS_BUILD_DIR/publify_amazon_sidebar && bundle exec rake'
  - 'cd $TRAVIS_BUILD_DIR/publify_textfilter_code && bundle exec rake'

#after_success:
#  - bundle exec codeclimate-test-reporter

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 8850bccc6911d74965627b1fafe753beb368fab00d33de0c7576c6598fc1220e

notifications:
  webhooks:
    urls:
      - http://publify_hook.ookook.fr/travisci
    on_success: always
    on_failure: never
    on_start: never
